# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-24 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180424_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comic',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='comic',
            old_name='published_date',
            new_name='release_date',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='author',
        ),
        migrations.AddField(
            model_name='comic',
            name='publisher',
            field=models.ForeignKey(default='Independent', on_delete=django.db.models.deletion.CASCADE, related_name='comics', to='shop.Publisher'),
            preserve_default=False,
        ),
    ]
