# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-24 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180424_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publisher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comics', to='shop.Publisher')),
                ('description', models.TextField()),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                
            ],
        ),
    ]
