# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-24 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_comic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='release_date',
        ),
    ]
